### ISSUE TITLE
[3.60 Enso] iTLS package breaks PSN login

### ISSUE THREAD

**Issue by HindrikStegenga** [SKGleba/iTLS-Enso#15] opened 2020-03-16 17:55 UTC
After installing the iTLS full enso package on my 3.60 Enso vita, the PSN login breaks.
I was able to consistently reproduce the problem, the moment I disabled the iTLS tai plugin I could login again on PSN. 
It gives me a: NP-2239-6 error message.

**Comment by SKGleba** [comment] 2020-03-17 08:44
Could not reproduce here on 3 diff setups, please make sure that you dont have any conflicting plugins. Also try installing selectively.

**Comment by HindrikStegenga** [comment] 2020-03-17 09:41
Hmm, I will take a look at what happens when I selectively install them. Regarding the plugins, I only use storagemgr, nonprdrm, ref00d and adrenaline.

Update: It breaks the moment I install the in-app https&ssl modules.
I can install the plugin itself and everything else just fine.

**Comment by HindrikStegenga** [comment] 2020-03-18 20:36
After cleaning all the plugins and only installing the following plugins (most up to date versions):
*kernel
storagemgr.skprx (vita2sd)
nonpdrm.skprx
0syscall6.skprx
adrenaline_kernel.skprx
iTLS.skprx

*main
download_enabler.suprx
shellbat_mod.suprx
henkaku.suprx

The problem still persists that PSN gives me a NP-2239-6 whenever I enable the in-app http&ssl modules. When I disable only that part of iTLS, I can login on PSN again. Switching out memorycards or disabling sd2vita or any of the other plugins made no difference at all. (I tried with only iTLS and henkaku enabled, all other plugins disabled, but no dice either)

**Comment by angela-dayo** [comment] 2020-03-24 03:03
Can confirm that I am able to reproduce the same issue on both a VitaTV and Vita, both on 3.60.

To reproduce, have `itls.skprx` enabled and loaded (following a "Full" installation), and then try to navigate to Settings → PlayStation Network. This should result in you receiving an NP-2239-6 error. Performing further actions (such as System Activation) will all similarly fail with the same error code.

Disabling `itls.skprx` will restore impacted functionality.

That being said, _other_ parts of PSN seem to work just fine — this includes trophy syncing, friends functionality, activities, messages, and the PS Store.

**Comment by AceCuba** [comment] 2020-10-13 03:46
same problem here

**Comment by faelana** [comment] 2020-11-23 21:19
i confirm the same problem here

**Comment by ddw04** [comment] 2021-01-12 01:52
does this happen if you install only the new root certs?

**Comment by AceCuba** [comment] 2021-01-12 11:50
nop i install the full pakepage and the same hapend even if i just only install a few options

**Comment by ddw04** [comment] 2021-01-12 20:06
> nop i install the full pakepage and the same hapend even if i just only install a few options

sorry im a little confused, are the new root certs not just specific options within the full package? cause thats what was i was thinking. but the way your reply is, it seems the full package and the new root certs are 2 separate things altogether.

**Comment by lukeacat** [comment] 2021-02-19 08:28
same thing

**Comment by winebottle61** [comment] 2021-03-07 19:33
Just writing to say that I'm also experiencing this issue.

Running Enso 3.60. After installing iTLS Enso (full package) I kept getting this error when I try to login. It logs me in and I can still access the PlayStation store however I can't seem to activate my system for games but otherwise I'm not sure what harm is being done. I narrowed it down to the "in-app" modules, it's the one responsible for the error. 

At first i uninstalled the module to be safe however Crunchyroll doesn't seem to work without it (using the modded Crunchyroll app). Not sure what other apps are affected. My current workaround is simply uninstalling and reinstalling the "in-app" module as needed. Not sure if there are conflicting plugins, I got all the normal stuff like sd2vita, homebrew browser, autoplugin, adrenaline etc. If someone has the time to do a fresh install and update us if the error is still occurring that would be dope.

Sorry if I wrote anything wrong, I just got my vita this week, really don't know anything. Thank you for providing these amazing tools, the vita wouldn't be worth it without you guys adding these must have plugins.

**Comment by SKGleba** [comment] 2021-04-19 15:44
This is a tough one, it seems that some obscure NP (PSN) structure changed around 3.65. To get it to work on 3.60 would require either replacing half of sys modules or finding all usages of the specific calls that changed.
Also it works fine on 3.65 so this is a #wontfix, sorry guys.

**The workaround is to simply disable inapp patches when logging in to PSN.**

**Comment by HindrikStegenga** [comment] 2021-04-24 12:37
Unfortunate but understandable. Thank you for taking a look at it anyway!

**Comment by SKGleba** [comment] 2021-06-11 08:02
ehh, gonna take another look at it now that sony locked psn store to tls1.2

**Comment by SKGleba** [comment] 2021-06-12 15:35
turns out that
- sony blocked the store to new certs only
- the iTLS PSN login error on 3.60 is caused by shell failing some handshake with PSN (yes, settings/store IPC shell to call PSN).
`shell.elf_812bd268(0x30009, 0x81665B98, 0x400, 0x81602DFC) returned 0x80550F17`

**Comment by Richi08** [comment] 2021-06-13 22:29
Yeh currently just ran into this issue. Is this now a possible fix you reckon for 3.60 enso users ?

**Comment by soup6020** [comment] 2021-06-14 18:42
> Yeh currently just ran into this issue. Is this now a possible fix you reckon for 3.60 enso users ?

Move to 3.65. It's functionally equivalent anyways. There's an easy way to migrate with VitaDeploy, another SKGleba program.

**Comment by eze92** [comment] 2021-06-18 15:33
If the plugins are used, without having enso, only h-encore, what error could it cause?

**Closed as completed** 2021-06-18 16:03 UTC
Labels: bug, wontfix
